//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 01:11:14 PM CST 
//


package com.hp.es.cto.sp.persistence.jaxb.subscription;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subscription_record complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subscription_record">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subscription_record_server" type="{http://www.hp.com/es/cto/sp/context/jaxb/subscription}subscription_record_server" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="owner_email" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="csa_org" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="context_node" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="project" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="start_time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="terminate_time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subscription_record", propOrder = {
    "subscriptionRecordServer"
})
public class SubscriptionRecord {

    @XmlElement(name = "subscription_record_server")
    protected List<SubscriptionRecordServer> subscriptionRecordServer;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String status;
    @XmlAttribute(name = "owner_email")
    protected String ownerEmail;
    @XmlAttribute(name = "csa_org")
    protected String csaOrg;
    @XmlAttribute(name = "context_node")
    protected String contextNode;
    @XmlAttribute
    protected String project;
    @XmlAttribute(name = "start_time")
    protected String startTime;
    @XmlAttribute(name = "terminate_time")
    protected String terminateTime;
    @XmlAttribute
    protected String property;

    /**
     * Gets the value of the subscriptionRecordServer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscriptionRecordServer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscriptionRecordServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubscriptionRecordServer }
     * 
     * 
     */
    public List<SubscriptionRecordServer> getSubscriptionRecordServer() {
        if (subscriptionRecordServer == null) {
            subscriptionRecordServer = new ArrayList<SubscriptionRecordServer>();
        }
        return this.subscriptionRecordServer;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the ownerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerEmail() {
        return ownerEmail;
    }

    /**
     * Sets the value of the ownerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerEmail(String value) {
        this.ownerEmail = value;
    }

    /**
     * Gets the value of the csaOrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsaOrg() {
        return csaOrg;
    }

    /**
     * Sets the value of the csaOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsaOrg(String value) {
        this.csaOrg = value;
    }

    /**
     * Gets the value of the contextNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextNode() {
        return contextNode;
    }

    /**
     * Sets the value of the contextNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextNode(String value) {
        this.contextNode = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the terminateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminateTime() {
        return terminateTime;
    }

    /**
     * Sets the value of the terminateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminateTime(String value) {
        this.terminateTime = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperty(String value) {
        this.property = value;
    }

}
