
GO
/****** Object:  Table [dbo].[GROUP_MAPPING]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_MAPPING](
	[UUID] [nvarchar](255) NOT NULL,
	[groupId] [nvarchar](255) NULL,
	[LDAP_GROUP] [nvarchar](255) NULL,
 CONSTRAINT [PK__GROUP_MA__65A475E7404EADD8] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LOGICAL_GROUP]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGICAL_GROUP](
	[UUID] [nvarchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[NAME] [nvarchar](255) NULL,
	[organizationId] [nvarchar](255) NULL,
 CONSTRAINT [PK__LOGICAL___65A475E72CE1BACD] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ORGANIZATION]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORGANIZATION](
	[UUID] [nvarchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[CSA_ORGANIZATION_ID] [nvarchar](255) NULL,
	[IS_SSL] [bit] NULL,
	[LDAP_SERVER] [nvarchar](255) NULL,
	[NAME] [nvarchar](255) NULL,
	[PASSWORD] [nvarchar](255) NULL,
	[PORT] [nvarchar](255) NULL,
	[SEARCH_BASE] [nvarchar](255) NULL,
	[USERNAME] [nvarchar](255) NULL,
 CONSTRAINT [PK__ORGANIZA__65A475E704BDE546] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PROVIDER_KEY]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_KEY](
	[UUID] [nvarchar](255) NOT NULL,
	[AVAILABILITY_ZONE] [nvarchar](255) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CSA_PROVIDER_ID] [nvarchar](255) NULL,
	[KEY_FILE] [varbinary](max) NULL,
	[PASSWORD] [nvarchar](255) NULL,
	[USERNAME] [nvarchar](255) NULL,
	[NAME] [nvarchar](255) NULL,
 CONSTRAINT [PK__PROVIDER__65A475E7A4D8EF0F] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USER_KEY]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER_KEY](
	[UUID] [nvarchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[KEY_FILE] [varbinary](max) NULL,
	[LDAP_EMAIL] [nvarchar](255) NULL,
	[NAME] [nvarchar](255) NULL,
 CONSTRAINT [PK__USER_KEY__65A475E73E6C1298] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK_PROVIDER_KEY_AZ]    Script Date: 1/16/2014 8:20:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_PROVIDER_KEY_AZ] ON [dbo].[PROVIDER_KEY]
(
	[CSA_PROVIDER_ID] ASC,
	[AVAILABILITY_ZONE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK_PROVIDER_KEY_NAME]    Script Date: 1/16/2014 8:20:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_PROVIDER_KEY_NAME] ON [dbo].[PROVIDER_KEY]
(
	[CSA_PROVIDER_ID] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK_USER_KEY]    Script Date: 1/16/2014 8:20:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_USER_KEY] ON [dbo].[USER_KEY]
(
	[LDAP_EMAIL] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_MAPPING_LOGICAL_GROUP] FOREIGN KEY([groupId])
REFERENCES [dbo].[LOGICAL_GROUP] ([UUID])
GO
ALTER TABLE [dbo].[GROUP_MAPPING] CHECK CONSTRAINT [FK_GROUP_MAPPING_LOGICAL_GROUP]
GO
ALTER TABLE [dbo].[LOGICAL_GROUP]  WITH CHECK ADD  CONSTRAINT [FK_LOGICAL_GROUP_ORGANIZATION] FOREIGN KEY([organizationId])
REFERENCES [dbo].[ORGANIZATION] ([UUID])
GO
ALTER TABLE [dbo].[LOGICAL_GROUP] CHECK CONSTRAINT [FK_LOGICAL_GROUP_ORGANIZATION]
GO
