GO
/****** Object:  Table [dbo].[PROVIDER_SERVER]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVIDER_SERVER](
	[UUID] [nvarchar](50) NOT NULL,
	[CSA_PROVIDER_ID] [nvarchar](50) NULL,
	[NAME] [nvarchar](50) NULL,
	[IP_ADDRESS] [nvarchar](50) NULL,
	[PRIVATE_IP_ADDRESS] [nvarchar](50) NULL,
	[PUBLIC_IP_ADDRESS] [nvarchar](50) NULL,
	[SIZE] [nvarchar](50) NULL,
	[OS_TYPE] [nvarchar](50) NULL,
	[PROVIDER] [nvarchar](50) NULL,
	[ISALLOCATED] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_PROVIDER_SERVER_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ipAddress] ON [dbo].[PROVIDER_SERVER] 
(
	[IP_ADDRESS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NameAndProvider] ON [dbo].[PROVIDER_SERVER] 
(
	[CSA_PROVIDER_ID] ASC,
	[NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [privateIP] ON [dbo].[PROVIDER_SERVER] 
(
	[PRIVATE_IP_ADDRESS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [publicIP] ON [dbo].[PROVIDER_SERVER] 
(
	[PUBLIC_IP_ADDRESS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_META_DATA]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_META_DATA](
	[UUID] [nvarchar](50) NOT NULL,
	[LEVEL] [int] NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[CSA_ORG_ID] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_META_DATA] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Org_Level] ON [dbo].[CONTEXT_META_DATA] 
(
	[LEVEL] ASC,
	[CSA_ORG_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Org_Name] ON [dbo].[CONTEXT_META_DATA] 
(
	[NAME] ASC,
	[CSA_ORG_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_NODE]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_NODE](
	[UUID] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[CONTEXT_META_DATA_ID] [nvarchar](50) NULL,
	[PARENT_NODE_ID] [nvarchar](50) NULL,
	[DISPLAY_NAME] [nvarchar](50) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_NODE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Name_MetaData] ON [dbo].[CONTEXT_NODE] 
(
	[NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [DisplayName_MetaData] ON [dbo].[CONTEXT_NODE] 
(
	[DISPLAY_NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Name_Parent] ON [dbo].[CONTEXT_NODE] 
(
	[DISPLAY_NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC,
	[PARENT_NODE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [DisplayName_Parent] ON [dbo].[CONTEXT_NODE] 
(
	[DISPLAY_NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC,
	[PARENT_NODE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_NODE_PROVIDER_MAPPING]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_NODE_PROVIDER_MAPPING](
	[UUID] [nvarchar](50) NOT NULL,
	[CSA_PROVIDER_ID] [nvarchar](50) NULL,
	[CONTEXT_NODE_ID] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_NODE_PROVIDER_MAPPING] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_NODE_LDAP_MAPPING]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_NODE_LDAP_MAPPING](
	[UUID] [nvarchar](50) NOT NULL,
	[CONTEXT_NODE_ID] [nvarchar](50) NULL,
	[LDAP_DN] [nvarchar](max) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_NODE_LDAP_MAPPING] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_CONTEXT_NODE_CONTEXT_META_DATA]    Script Date: 07/07/2014 16:02:59 ******/
ALTER TABLE [dbo].[CONTEXT_NODE]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_META_DATA] FOREIGN KEY([CONTEXT_META_DATA_ID])
REFERENCES [dbo].[CONTEXT_META_DATA] ([UUID])
GO
ALTER TABLE [dbo].[CONTEXT_NODE] CHECK CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_META_DATA]
GO
ALTER TABLE [dbo].[CONTEXT_NODE]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_NODE] FOREIGN KEY([PARENT_NODE_ID])
REFERENCES [dbo].[CONTEXT_NODE] ([UUID])
GO
ALTER TABLE [dbo].[CONTEXT_NODE] CHECK CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_NODE]
GO
/****** Object:  ForeignKey [FK_CONTEXT_NODE_PROVIDER_MAPPING_CONTEXT_NODE]    Script Date: 07/07/2014 16:02:59 ******/
ALTER TABLE [dbo].[CONTEXT_NODE_PROVIDER_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_PROVIDER_MAPPING_CONTEXT_NODE] FOREIGN KEY([CONTEXT_NODE_ID])
REFERENCES [dbo].[CONTEXT_NODE] ([UUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CONTEXT_NODE_PROVIDER_MAPPING] CHECK CONSTRAINT [FK_CONTEXT_NODE_PROVIDER_MAPPING_CONTEXT_NODE]
GO
/****** Object:  ForeignKey [FK_CONTEXT_NODE_LDAP_MAPPING_CONTEXT_NODE]    Script Date: 07/07/2014 16:02:59 ******/
ALTER TABLE [dbo].[CONTEXT_NODE_LDAP_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_LDAP_MAPPING_CONTEXT_NODE] FOREIGN KEY([CONTEXT_NODE_ID])
REFERENCES [dbo].[CONTEXT_NODE] ([UUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CONTEXT_NODE_LDAP_MAPPING] CHECK CONSTRAINT [FK_CONTEXT_NODE_LDAP_MAPPING_CONTEXT_NODE]
GO
/****** Object:  Table [dbo].[SUBSCRIPTION]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION](
	[UUID] [varchar](255) NOT NULL,
	[CONTEXT_NODE_ID] [varchar](255) NULL,
	[CSA_ORG_ID] [varchar](255) NULL,
	[NAME] [varchar](255) NULL,
	[OWNER_ID] [varchar](255) NULL,
	[PROJECT] [varchar](255) NULL,
	[START_TIME] [datetime2](7) NULL,
	[STATUS] [varchar](255) NULL,
	[TERMINATE_TIME] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_SHARED_RESOURCE]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_SHARED_RESOURCE](
	[UUID] [varchar](255) NOT NULL,
	[CREATE_DATE] [datetime2](7) NULL,
	[CSA_PROVIDER_ID] [varchar](255) NULL,
	[CURRENT_CONNECTION] [int] NULL,
	[MAX_CONNECTION] [int] NULL,
	[NAME] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUBSCRIPTION_SERVER]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION_SERVER](
	[UUID] [varchar](255) NOT NULL,
	[CSA_PROVIDER_ID] [varchar](255) NULL,
	[DNS] [varchar](255) NULL,
	[IAAS_PROVIDER] [varchar](255) NULL,
	[IP_ADDRESS] [varchar](255) NULL,
	[PRIVATE_IP_ADDRESS] [varchar](255) NULL,
	[PUBLIC_IP_ADDRESS] [varchar](255) NULL,
	[SIMPLIFIED_DNS] [varchar](255) NULL,
	[SIZE] [varchar](255) NULL,
	[SUBSCRIPTION_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUBSCRIPTION_PROPERTY]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION_PROPERTY](
	[UUID] [varchar](255) NOT NULL,
	[PROPERTY_NAME] [varchar](255) NULL,
	[PROPERTY_VALUE] [varchar](255) NULL,
	[SUBSCRIPTION_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUBSCRIPTION_SERVER_PRODUCT]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION_SERVER_PRODUCT](
	[UUID] [varchar](255) NOT NULL,
	[PRODCUT_NAME] [varchar](255) NULL,
	[SERVER_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK47D6D4A5F1CB807C]    Script Date: 08/05/2014 01:48:52 ******/
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER]  WITH CHECK ADD  CONSTRAINT [FK47D6D4A5F1CB807C] FOREIGN KEY([SUBSCRIPTION_ID])
REFERENCES [dbo].[SUBSCRIPTION] ([UUID])
GO
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER] CHECK CONSTRAINT [FK47D6D4A5F1CB807C]
GO
/****** Object:  ForeignKey [FK200EAEB7F1CB807C]    Script Date: 08/05/2014 01:48:52 ******/
ALTER TABLE [dbo].[SUBSCRIPTION_PROPERTY]  WITH CHECK ADD  CONSTRAINT [FK200EAEB7F1CB807C] FOREIGN KEY([SUBSCRIPTION_ID])
REFERENCES [dbo].[SUBSCRIPTION] ([UUID])
GO
ALTER TABLE [dbo].[SUBSCRIPTION_PROPERTY] CHECK CONSTRAINT [FK200EAEB7F1CB807C]
GO
/****** Object:  ForeignKey [FKF2C75F35869350B9]    Script Date: 08/05/2014 01:48:52 ******/
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER_PRODUCT]  WITH CHECK ADD  CONSTRAINT [FKF2C75F35869350B9] FOREIGN KEY([SERVER_ID])
REFERENCES [dbo].[SUBSCRIPTION_SERVER] ([UUID])
GO
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER_PRODUCT] CHECK CONSTRAINT [FKF2C75F35869350B9]
GO
/****** Object:  Table [dbo].[PROJECT]    Script Date: 08/15/2014 11:29:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROJECT](
	[UUID] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[CSA_ORGANIZATION_ID] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PROJECT] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE UNIQUE NONCLUSTERED INDEX [Name_Org] ON [dbo].[PROJECT] 
(
	[NAME] ASC,
	[CSA_ORGANIZATION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROJECT_LDAP_MAPPING]    Script Date: 08/15/2014 11:31:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROJECT_LDAP_MAPPING](
	[UUID] [nvarchar](50) NOT NULL,
	[TYPE] [nvarchar](50) NOT NULL,
	[PROJECT_ID] [nvarchar](50) NOT NULL,
	[LDAP_DN] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_PROJECT_LDAP_MAPPING] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PROJECT_LDAP_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_PROJECT_LDAP_MAPPING_PROJECT] FOREIGN KEY([PROJECT_ID])
REFERENCES [dbo].[PROJECT] ([UUID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PROJECT_LDAP_MAPPING] CHECK CONSTRAINT [FK_PROJECT_LDAP_MAPPING_PROJECT]
GO

