GO
DROP INDEX [DisplayName_Parent] ON [dbo].[CONTEXT_NODE] 
GO
DROP INDEX [Name_MetaData] ON [dbo].[CONTEXT_NODE] 
GO
CREATE UNIQUE NONCLUSTERED INDEX [DisplayName_Parent] ON [dbo].[CONTEXT_NODE] 
(
	[DISPLAY_NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC,
	[PARENT_NODE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
DROP INDEX [Name_Parent] ON [dbo].[CONTEXT_NODE] 
GO
DROP INDEX [DisplayName_MetaData] ON [dbo].[CONTEXT_NODE] 
GO
CREATE UNIQUE NONCLUSTERED INDEX [Name_Parent] ON [dbo].[CONTEXT_NODE] 
(
	[NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC,
	[PARENT_NODE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO