GO
/****** Object:  Table [dbo].[PROVIDER_REGION]    Script Date: 12/8/2014 5:45:25 PM ******/
DROP TABLE [dbo].[PROVIDER_REGION]
GO
/****** Object:  Table [dbo].[DESIGN_PROVIDER_SIZE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'MESSAGE' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ALTER COLUMN MESSAGE varchar(max) NULL;
END  
ELSE
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ADD MESSAGE varchar(max) NULL;
END 
GO

IF EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'LOG_DETAIL' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ALTER COLUMN LOG_DETAIL varchar(max) NULL;
END  
ELSE
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ADD LOG_DETAIL varchar(max) NULL;
END 
GO

IF NOT EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'LOG_PATH' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] add LOG_PATH varchar(255) NULL;
END  
GO

IF NOT EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'LOG_TAG' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] add LOG_TAG varchar(255) NULL;
END 
GO

CREATE TABLE [dbo].[DESIGN_PROVIDER_SIZE](
	[UUID] [varchar](255) NOT NULL,
	[SERVICE_DESIGN_ID] [varchar](255) NOT NULL,
	[PROVIDER_SIZE_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DESIGN_PROVIDER_SIZE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORG_PROVIDER_SIZE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORG_PROVIDER_SIZE](
	[UUID] [varchar](255) NOT NULL,
	[ORG_ID] [varchar](255) NOT NULL,
	[PROVIDER_SIZE_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ORG_PROVIDER_SIZE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_REGION]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_REGION](
	[UUID] [varchar](255) NOT NULL,
	[PROVIDER_TYPE_ID] [varchar](255) NOT NULL,
	[REGION_NAME] [varchar](255) NOT NULL,
	[REGION_DISPLAY_NAME] [varchar](255) NOT NULL,
 CONSTRAINT [PK_PROVIDER_REGION] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_regionname]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_regionname] ON [dbo].[PROVIDER_REGION]
(
	[PROVIDER_TYPE_ID] ASC,
	[REGION_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_REGION_AZ]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_REGION_AZ](
	[UUID] [varchar](255) NOT NULL,
	[REGION_ID] [varchar](255) NOT NULL,
	[AZ] [varchar](255) NOT NULL,
 CONSTRAINT [PK_PROVIDER_REGION_AZ] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_regionname]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [region_az] ON [dbo].[PROVIDER_REGION_AZ]
(
	[REGION_ID] ASC,
	[AZ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_SIZE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_SIZE](
	[UUID] [varchar](255) NOT NULL,
	[PROVIDER_TYPE_ID] [varchar](255) NOT NULL,
	[SIZE] [varchar](255) NOT NULL,
	[DISPLAY_NAME] [varchar](255) NULL,
	[FLAVOR] [varchar](255) NULL,
	[VCPU] [varchar](255) NULL,
	[VMEMORY] [varchar](255) NULL,
 CONSTRAINT [PK_PROVIDER_SIZE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_size]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_size] ON [dbo].[PROVIDER_SIZE]
(
	[PROVIDER_TYPE_ID] ASC,
	[SIZE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [type_size]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_displayname] ON [dbo].[PROVIDER_SIZE]
(
	[PROVIDER_TYPE_ID] ASC,
	[DISPLAY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_TYPE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_TYPE](
	[UUID] [varchar](255) NOT NULL,
	[TYPE] [varchar](255) NOT NULL,
	[SUB_TYPE] [varchar](255) NOT NULL,
 CONSTRAINT [PK_PROVIDER_TYPE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_subtype]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_subtype] ON [dbo].[PROVIDER_TYPE]
(
	[TYPE] ASC,
	[SUB_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORG_PROVIDER_REGION]    Script Date: 1/6/2015 9:45:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORG_PROVIDER_REGION](
	[UUID] [nvarchar](255) NOT NULL,
	[ORG_ID] [varchar](255) NOT NULL,
	[PROVIDER_REGION_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ORG_PROVIDER_REGION] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORG_PROVIDER_TYPE]    Script Date: 1/6/2015 9:46:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORG_PROVIDER_TYPE](
	[UUID] [varchar](255) NOT NULL,
	[ORG_ID] [varchar](255) NOT NULL,
	[PROVIDER_TYPE_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ORG_PROVIDER_TYPE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[ORG_PROVIDER_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_ORG_PROVIDER_TYPE_PROVIDER_TYPE] FOREIGN KEY([PROVIDER_TYPE_ID])
REFERENCES [dbo].[PROVIDER_TYPE] ([UUID])
GO
ALTER TABLE [dbo].[ORG_PROVIDER_TYPE] CHECK CONSTRAINT [FK_ORG_PROVIDER_TYPE_PROVIDER_TYPE]
GO
ALTER TABLE [dbo].[ORG_PROVIDER_REGION]  WITH CHECK ADD  CONSTRAINT [FK_ORG_PROVIDER_REGION_PROVIDER_REGION] FOREIGN KEY([PROVIDER_REGION_ID])
REFERENCES [dbo].[PROVIDER_REGION] ([UUID])
GO
ALTER TABLE [dbo].[ORG_PROVIDER_REGION] CHECK CONSTRAINT [FK_ORG_PROVIDER_REGION_PROVIDER_REGION]
GO
ALTER TABLE [dbo].[DESIGN_PROVIDER_SIZE]  WITH CHECK ADD  CONSTRAINT [FK_DESIGN_PROVIDER_SIZE_PROVIDER_SIZE] FOREIGN KEY([PROVIDER_SIZE_ID])
REFERENCES [dbo].[PROVIDER_SIZE] ([UUID])
GO
ALTER TABLE [dbo].[DESIGN_PROVIDER_SIZE] CHECK CONSTRAINT [FK_DESIGN_PROVIDER_SIZE_PROVIDER_SIZE]
GO
ALTER TABLE [dbo].[ORG_PROVIDER_SIZE]  WITH CHECK ADD  CONSTRAINT [FK_ORG_PROVIDER_SIZE_PROVIDER_SIZE] FOREIGN KEY([PROVIDER_SIZE_ID])
REFERENCES [dbo].[PROVIDER_SIZE] ([UUID])
GO
ALTER TABLE [dbo].[ORG_PROVIDER_SIZE] CHECK CONSTRAINT [FK_ORG_PROVIDER_SIZE_PROVIDER_SIZE]
GO
ALTER TABLE [dbo].[PROVIDER_REGION]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_REGION_PROVIDER_TYPE] FOREIGN KEY([PROVIDER_TYPE_ID])
REFERENCES [dbo].[PROVIDER_TYPE] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_REGION] CHECK CONSTRAINT [FK_PROVIDER_REGION_PROVIDER_TYPE]
GO
ALTER TABLE [dbo].[PROVIDER_REGION_AZ]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_REGION_AZ_PROVIDER_REGION] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[PROVIDER_REGION] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_REGION_AZ] CHECK CONSTRAINT [FK_PROVIDER_REGION_AZ_PROVIDER_REGION]
GO
ALTER TABLE [dbo].[PROVIDER_SIZE]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_SIZE_PROVIDER_TYPE] FOREIGN KEY([PROVIDER_TYPE_ID])
REFERENCES [dbo].[PROVIDER_TYPE] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_SIZE] CHECK CONSTRAINT [FK_PROVIDER_SIZE_PROVIDER_TYPE]
GO
ALTER TABLE [dbo].[PROVIDER_KEY] WITH CHECK ADD	[REGION_ID] [varchar](255) NULL
GO
ALTER TABLE [dbo].[PROVIDER_KEY]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_KEY_PROVIDER_REGION] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[PROVIDER_REGION] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_KEY] CHECK CONSTRAINT [FK_PROVIDER_KEY_PROVIDER_REGION]
GO

INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'hpcs', 'hpcs')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'ospool', 'default')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'vmware', 'octo')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'openstack', 'openstackInstance')
GO

INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'xsmall', 'standard.xsmall', '1', '1', 'standard.xsmall(1vcpu, 1G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'small', 'standard.small', '2', '2', 'standard.small(2vcpu, 2G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'medium', 'standard.medium', '2', '4', 'standard.medium(2vcpu, 4G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'large', 'standard.large', '4', '8', 'standard.large(4vcpu, 8G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'xlarge', 'standard.xlarge', '4', '15', 'standard.xlarge(4vcpu, 15G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'highmemlarge', 'highmem.large', '4', '16', 'highmem.large(4vcpu, 16G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), '2xlarge', 'standard.2xlarge', '8', '30', 'standard.2xlarge(8vcpu, 30G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'highmemxlarge', 'highmem.xlarge', '4', '30', 'highmem.xlarge(4vcpu, 30G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), '4xlarge', 'standard.4xlarge', '12', '60', 'standard.4xlarge(12vcpu, 60G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'highmem2xlarge', 'highmem.2xlarge', '8', '60', 'highmem.2xlarge(8vcpu, 60G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), '8xlarge', 'standard.8xlarge', '16', '120', 'standard.8xlarge(16vcpu, 120G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'small', 'small', '2', '4', 'small')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'medium', 'medium', '4', '8', 'medium')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'large', 'large', '8', '16', 'large')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'xlarge', 'xlarge', '16', '32', 'xlarge')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'small', 'small', '2', '2', 'small(2vcpu, 2G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'medium', 'medium', '2', '4', 'medium(2vcpu, 4G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'large', 'large', '4', '8', 'large(4vcpu, 8G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'xlarge', 'xlarge', '4', '16', 'xlarge(4vcpu, 16G vmemory)')
GO

INSERT INTO dbo.PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME, REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'region-a.geo-1', 'US WEST')
GO
INSERT INTO dbo.PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'region-b.geo-1', 'US EAST')
GO

INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1'), 'az1')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1'), 'az2')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1'), 'az3')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1'), 'az1')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1'), 'az2')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1'), 'az3')
GO


UPDATE [dbo].[PROVIDER_KEY]
   SET [REGION_ID] = (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1')
WHERE [REGION_NAME] ='region-a.geo-1'
GO
GO
UPDATE [dbo].[PROVIDER_KEY]
   SET [REGION_ID] = (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1')
WHERE [REGION_NAME] ='region-b.geo-1'
GO
