GO

/****** Object:  Table [dbo].[SUBSCRIPTION_LOG]    Script Date: 10/11/2014 6:17:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SUBSCRIPTION_LOG](
	[UUID] [varchar](255) NOT NULL,
	[COMPONENT] [varchar](255) NULL,
	[EVENT] [varchar](255) NULL,
	[LOG_LEVEL] [varchar](255) NULL,
	[LOG_TIME] [datetime] NULL,
	[MESSAGE] [varchar](max) NULL,
	[SUBSCRIPTION_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SUBSCRIPTION_LOG]  WITH CHECK ADD  CONSTRAINT [FKF1B1C102F1CB807C] FOREIGN KEY([SUBSCRIPTION_ID])
REFERENCES [dbo].[SUBSCRIPTION] ([UUID])
GO

ALTER TABLE [dbo].[SUBSCRIPTION_LOG] CHECK CONSTRAINT [FKF1B1C102F1CB807C]
GO

/****** Object:  Table [dbo].[SUBSCRIPTION_SERVER]    Script Date: 10/11/2014 6:17:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER] add ACTIVE_FLAG varchar(255);

GO
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER] add OS_TYPE varchar(255);

GO

UPDATE [dbo].[SUBSCRIPTION_SERVER] set OS_TYPE='linux';
GO
