-- for R4.2 and R5 to enable the aws

INSERT INTO PROVIDER_TYPE(UUID, TYPE, SUB_TYPE)
VALUES(uuid_generate_v4(), 'aws', 'ec2');
INSERT INTO PROVIDER_TYPE(UUID, TYPE, SUB_TYPE)
VALUES(uuid_generate_v4(), 'ecsvpc', 'rhel');
INSERT INTO PROVIDER_TYPE(UUID, TYPE, SUB_TYPE)
VALUES(uuid_generate_v4(), 'ecsvpc', 'windows');


INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.medium', 'm3.medium', '1', '3.75', 'm3.medium(1vcpu, 3.75G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.large', 'm3.large', '2', '7.5', 'm3.large(2vcpu, 7.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.xlarge', 'm3.xlarge', '4', '15', 'm3.xlarge(2vcpu, 15G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.2xlarge', 'm3.2xlarge', '8', '30', 'm3.2xlarge(8vcpu, 30G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.small', 'm1.small', '1', '1.7', 'm1.small(1vcpu, 1.7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.medium', 'm1.medium', '1', '3.7', 'm1.medium(1vcpu, 3.7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.large', 'm1.large', '2', '7.5', 'm1.large(2vcpu, 7.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.xlarge', 'm1.xlarge', '4', '15', 'm1.xlarge(4vcpu, 15G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.large', 'c3.large', '2', '3.75', 'c3.large(2vcpu, 3.75G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.xlarge', 'c3.xlarge', '4', '7.5', 'c3.xlarge(4vcpu, 7.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.2xlarge', 'c3.2xlarge', '8', '15', 'c3.2xlarge(8vcpu, 15G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.4xlarge', 'c3.4xlarge', '16', '30', 'c3.4xlarge(16vcpu, 30G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.8xlarge', 'c3.8xlarge', '32', '60', 'c3.8xlarge(16vcpu, 30G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c1.medium', 'c1.medium', '2', '1.7', 'c1.medium(2vcpu, 1.7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c1.xlarge', 'c1.xlarge', '8', '7', 'c1.xlarge(8vcpu, 7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm2.xlarge', 'm2.xlarge', '2', '17.1', 'm2.xlarge(2vcpu, 17.1G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm2.2xlarge', 'm2.2xlarge', '4', '34.2', 'm2.2xlarge(4vcpu, 34.2G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm2.4xlarge', 'm2.4xlarge', '8', '68.4', 'm2.4xlarge(8vcpu, 68.4G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'hi1.4xlarge', 'hi1.4xlarge', '16', '60.5', 'hi1.4xlarge(16vcpu, 60.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'hs1.8xlarge', 'hs1.8xlarge', '16', '117', 'hs1.8xlarge(16vcpu, 117G vmemory)');

INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'small_highperformance', 'f8924475-40d0-3840-8491-83faa3109b1b', '2', '4', 'High Performance Server - 2vCPU 4GMemory');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'small_standarad', 'c0c3a9fb-8385-38e0-ba46-adadde9af3bf', '2', '4', 'Standard Client Managed Server - 2vCPU 4GMemory');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'xsmall_highperformance', '7fe3d16a-83f6-33a0-a7f1-c029536bebe7', '1', '2', 'High Performance Server - 1vCPU 2GMemory');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'xsmall_standard', 'b219f59c-2dd5-36ab-badb-cecfc2277659', '1', '2', 'Standard Client Managed Server - 1vCPU 2GMemory');

INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'small_highperformance', '27bc42aa-eb15-30e8-b949-a69ebeb4eb4c', '2', '4', 'High Performance Server - 2vCPU 4GMemory');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'small_standarad', 'afc26371-29ad-3044-85e0-7d2c0e6b0688', '2', '4', 'Standard Client Managed Server - 2vCPU 4GMemory');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'xsmall_highperformance', 'b59c21a0-78fd-3074-a675-0e91ed19fb21', '1', '2', 'High Performance Server - 1vCPU 2GMemory');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'xsmall_standard', '6412121c-bb2d-32cb-9e46-0cfee7046be2', '1', '2', 'Standard Client Managed Server - 1vCPU 2GMemory');


INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'us-east-1','US East (N.Virginia)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'us-west-2','US West (Oregon)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'us-west-1','US West (N. California)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'eu-west-1','EU (Ireland)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'ap-southeast-1','Asia Pacific (Singapore)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'ap-southeast-2','Asia Pacific (Sydney)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'ap-northeast-1','Asia Pacific (Tokyo)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'sa-east-1','South America (Sao Paulo)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'eu-central-1','EU (Frankfurt)');

INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1d');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1e');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-2'), 'us-west-2a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-2'), 'us-west-2b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-2'), 'us-west-2c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-1'), 'us-west-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-1'), 'us-west-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-west-1'), 'eu-west-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-west-1'), 'eu-west-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-west-1'), 'eu-west-1c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-central-1'), 'eu-central-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-central-1'), 'eu-central-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-central-1'), 'eu-central-1c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-1'), 'ap-southeast-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-1'), 'ap-southeast-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-northeast-1'), 'ap-northeast-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-northeast-1'), 'ap-northeast-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-northeast-1'), 'ap-northeast-1c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-2'), 'ap-southeast-2a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-2'), 'ap-southeast-2b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='sa-east-1'), 'sa-east-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(uuid_generate_v4(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='sa-east-1'), 'sa-east-1b');
