
GO
/****** Object:  Table [dbo].[GROUP_MAPPING]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GROUP_MAPPING](
	[UUID] [nvarchar](255) NOT NULL,
	[groupId] [nvarchar](255) NULL,
	[LDAP_GROUP] [nvarchar](255) NULL,
 CONSTRAINT [PK__GROUP_MA__65A475E7404EADD8] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LOGICAL_GROUP]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGICAL_GROUP](
	[UUID] [nvarchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[NAME] [nvarchar](255) NULL,
	[organizationId] [nvarchar](255) NULL,
 CONSTRAINT [PK__LOGICAL___65A475E72CE1BACD] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ORGANIZATION]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORGANIZATION](
	[UUID] [nvarchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[CSA_ORGANIZATION_ID] [nvarchar](255) NULL,
	[IS_SSL] [bit] NULL,
	[LDAP_SERVER] [nvarchar](255) NULL,
	[NAME] [nvarchar](255) NULL,
	[PASSWORD] [nvarchar](255) NULL,
	[PORT] [nvarchar](255) NULL,
	[SEARCH_BASE] [nvarchar](255) NULL,
	[USERNAME] [nvarchar](255) NULL,
 CONSTRAINT [PK__ORGANIZA__65A475E704BDE546] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PROVIDER_KEY]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_KEY](
	[UUID] [nvarchar](255) NOT NULL,
	[AVAILABILITY_ZONE] [nvarchar](255) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CSA_PROVIDER_ID] [nvarchar](255) NULL,
	[KEY_FILE] [varbinary](max) NULL,
	[PASSWORD] [nvarchar](255) NULL,
	[USERNAME] [nvarchar](255) NULL,
	[NAME] [nvarchar](255) NULL,
 CONSTRAINT [PK__PROVIDER__65A475E7A4D8EF0F] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USER_KEY]    Script Date: 1/16/2014 8:20:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USER_KEY](
	[UUID] [nvarchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[KEY_FILE] [varbinary](max) NULL,
	[LDAP_EMAIL] [nvarchar](255) NULL,
	[NAME] [nvarchar](255) NULL,
 CONSTRAINT [PK__USER_KEY__65A475E73E6C1298] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK_PROVIDER_KEY_AZ]    Script Date: 1/16/2014 8:20:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_PROVIDER_KEY_AZ] ON [dbo].[PROVIDER_KEY]
(
	[CSA_PROVIDER_ID] ASC,
	[AVAILABILITY_ZONE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK_PROVIDER_KEY_NAME]    Script Date: 1/16/2014 8:20:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_PROVIDER_KEY_NAME] ON [dbo].[PROVIDER_KEY]
(
	[CSA_PROVIDER_ID] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK_USER_KEY]    Script Date: 1/16/2014 8:20:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_USER_KEY] ON [dbo].[USER_KEY]
(
	[LDAP_EMAIL] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GROUP_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_MAPPING_LOGICAL_GROUP] FOREIGN KEY([groupId])
REFERENCES [dbo].[LOGICAL_GROUP] ([UUID])
GO
ALTER TABLE [dbo].[GROUP_MAPPING] CHECK CONSTRAINT [FK_GROUP_MAPPING_LOGICAL_GROUP]
GO
ALTER TABLE [dbo].[LOGICAL_GROUP]  WITH CHECK ADD  CONSTRAINT [FK_LOGICAL_GROUP_ORGANIZATION] FOREIGN KEY([organizationId])
REFERENCES [dbo].[ORGANIZATION] ([UUID])
GO
ALTER TABLE [dbo].[LOGICAL_GROUP] CHECK CONSTRAINT [FK_LOGICAL_GROUP_ORGANIZATION]
GO

CREATE TABLE [dbo].[PROVIDER_REGION](
	[UUID] [varchar](255) NOT NULL,
	[IAAS_PROVIDER] [varchar](255) NULL,
	[REGION_NAME] [varchar](255) NULL,
 CONSTRAINT [PK_PROVIDER_REGION] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [UK_PROVIDER_REGION] ON [dbo].[PROVIDER_REGION]
(
	[IAAS_PROVIDER] ASC,
	[REGION_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

ALTER TABLE dbo.PROVIDER_KEY ADD
	REGION_NAME varchar(255) NULL
GO
DROP INDEX [UK_PROVIDER_KEY_AZ] ON [dbo].[PROVIDER_KEY]
GO
ALTER TABLE dbo.PROVIDER_KEY
	DROP COLUMN AVAILABILITY_ZONE
GO

CREATE UNIQUE NONCLUSTERED INDEX [UK_PROVIDER_KEY_REGION] ON [dbo].[PROVIDER_KEY]
(
	[CSA_PROVIDER_ID] ASC,
	[REGION_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

INSERT INTO dbo.PROVIDER_REGION(UUID, IAAS_PROVIDER, REGION_NAME)
VALUES('HPCS-WEST-01', 'HPCS', 'region-a.geo-1')
GO
INSERT INTO dbo.PROVIDER_REGION(UUID, IAAS_PROVIDER, REGION_NAME)
VALUES('HPCS-EAST-01', 'HPCS', 'region-b.geo-1')
GO

GO
/****** Object:  Table [dbo].[PROVIDER_SERVER]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVIDER_SERVER](
	[UUID] [nvarchar](50) NOT NULL,
	[CSA_PROVIDER_ID] [nvarchar](50) NULL,
	[NAME] [nvarchar](50) NULL,
	[IP_ADDRESS] [nvarchar](50) NULL,
	[PRIVATE_IP_ADDRESS] [nvarchar](50) NULL,
	[PUBLIC_IP_ADDRESS] [nvarchar](50) NULL,
	[SIZE] [nvarchar](50) NULL,
	[OS_TYPE] [nvarchar](50) NULL,
	[PROVIDER] [nvarchar](50) NULL,
	[ISALLOCATED] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_PROVIDER_SERVER_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [ipAddress] ON [dbo].[PROVIDER_SERVER] 
(
	[IP_ADDRESS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NameAndProvider] ON [dbo].[PROVIDER_SERVER] 
(
	[CSA_PROVIDER_ID] ASC,
	[NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [privateIP] ON [dbo].[PROVIDER_SERVER] 
(
	[PRIVATE_IP_ADDRESS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [publicIP] ON [dbo].[PROVIDER_SERVER] 
(
	[PUBLIC_IP_ADDRESS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_META_DATA]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_META_DATA](
	[UUID] [nvarchar](50) NOT NULL,
	[LEVEL] [int] NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[CSA_ORG_ID] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_META_DATA] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Org_Level] ON [dbo].[CONTEXT_META_DATA] 
(
	[LEVEL] ASC,
	[CSA_ORG_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Org_Name] ON [dbo].[CONTEXT_META_DATA] 
(
	[NAME] ASC,
	[CSA_ORG_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_NODE]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_NODE](
	[UUID] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[CONTEXT_META_DATA_ID] [nvarchar](50) NULL,
	[PARENT_NODE_ID] [nvarchar](50) NULL,
	[DISPLAY_NAME] [nvarchar](50) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_NODE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Name_Parent] ON [dbo].[CONTEXT_NODE] 
(
	[NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC,
	[PARENT_NODE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [DisplayName_Parent] ON [dbo].[CONTEXT_NODE] 
(
	[DISPLAY_NAME] ASC,
	[CONTEXT_META_DATA_ID] ASC,
	[PARENT_NODE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_NODE_PROVIDER_MAPPING]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_NODE_PROVIDER_MAPPING](
	[UUID] [nvarchar](50) NOT NULL,
	[CSA_PROVIDER_ID] [nvarchar](50) NULL,
	[CONTEXT_NODE_ID] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_NODE_PROVIDER_MAPPING] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTEXT_NODE_LDAP_MAPPING]    Script Date: 07/07/2014 16:02:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTEXT_NODE_LDAP_MAPPING](
	[UUID] [nvarchar](50) NOT NULL,
	[CONTEXT_NODE_ID] [nvarchar](50) NULL,
	[LDAP_DN] [nvarchar](max) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTEXT_NODE_LDAP_MAPPING] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_CONTEXT_NODE_CONTEXT_META_DATA]    Script Date: 07/07/2014 16:02:59 ******/
ALTER TABLE [dbo].[CONTEXT_NODE]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_META_DATA] FOREIGN KEY([CONTEXT_META_DATA_ID])
REFERENCES [dbo].[CONTEXT_META_DATA] ([UUID])
GO
ALTER TABLE [dbo].[CONTEXT_NODE] CHECK CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_META_DATA]
GO
ALTER TABLE [dbo].[CONTEXT_NODE]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_NODE] FOREIGN KEY([PARENT_NODE_ID])
REFERENCES [dbo].[CONTEXT_NODE] ([UUID])
GO
ALTER TABLE [dbo].[CONTEXT_NODE] CHECK CONSTRAINT [FK_CONTEXT_NODE_CONTEXT_NODE]
GO
/****** Object:  ForeignKey [FK_CONTEXT_NODE_PROVIDER_MAPPING_CONTEXT_NODE]    Script Date: 07/07/2014 16:02:59 ******/
ALTER TABLE [dbo].[CONTEXT_NODE_PROVIDER_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_PROVIDER_MAPPING_CONTEXT_NODE] FOREIGN KEY([CONTEXT_NODE_ID])
REFERENCES [dbo].[CONTEXT_NODE] ([UUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CONTEXT_NODE_PROVIDER_MAPPING] CHECK CONSTRAINT [FK_CONTEXT_NODE_PROVIDER_MAPPING_CONTEXT_NODE]
GO
/****** Object:  ForeignKey [FK_CONTEXT_NODE_LDAP_MAPPING_CONTEXT_NODE]    Script Date: 07/07/2014 16:02:59 ******/
ALTER TABLE [dbo].[CONTEXT_NODE_LDAP_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_CONTEXT_NODE_LDAP_MAPPING_CONTEXT_NODE] FOREIGN KEY([CONTEXT_NODE_ID])
REFERENCES [dbo].[CONTEXT_NODE] ([UUID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CONTEXT_NODE_LDAP_MAPPING] CHECK CONSTRAINT [FK_CONTEXT_NODE_LDAP_MAPPING_CONTEXT_NODE]
GO
/****** Object:  Table [dbo].[SUBSCRIPTION]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION](
	[UUID] [varchar](255) NOT NULL,
	[CONTEXT_NODE_ID] [varchar](255) NULL,
	[CSA_ORG_ID] [varchar](255) NULL,
	[NAME] [varchar](255) NULL,
	[OWNER_ID] [varchar](255) NULL,
	[PROJECT] [varchar](255) NULL,
	[START_TIME] [datetime2](7) NULL,
	[STATUS] [varchar](255) NULL,
	[TERMINATE_TIME] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_SHARED_RESOURCE]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_SHARED_RESOURCE](
	[UUID] [varchar](255) NOT NULL,
	[CREATE_DATE] [datetime2](7) NULL,
	[CSA_PROVIDER_ID] [varchar](255) NULL,
	[CURRENT_CONNECTION] [int] NULL,
	[MAX_CONNECTION] [int] NULL,
	[NAME] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUBSCRIPTION_SERVER]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION_SERVER](
	[UUID] [varchar](255) NOT NULL,
	[CSA_PROVIDER_ID] [varchar](255) NULL,
	[DNS] [varchar](255) NULL,
	[IAAS_PROVIDER] [varchar](255) NULL,
	[IP_ADDRESS] [varchar](255) NULL,
	[PRIVATE_IP_ADDRESS] [varchar](255) NULL,
	[PUBLIC_IP_ADDRESS] [varchar](255) NULL,
	[SIMPLIFIED_DNS] [varchar](255) NULL,
	[SIZE] [varchar](255) NULL,
	[SUBSCRIPTION_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUBSCRIPTION_PROPERTY]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION_PROPERTY](
	[UUID] [varchar](255) NOT NULL,
	[PROPERTY_NAME] [varchar](255) NULL,
	[PROPERTY_VALUE] [varchar](255) NULL,
	[SUBSCRIPTION_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SUBSCRIPTION_SERVER_PRODUCT]    Script Date: 08/05/2014 01:48:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION_SERVER_PRODUCT](
	[UUID] [varchar](255) NOT NULL,
	[PRODCUT_NAME] [varchar](255) NULL,
	[SERVER_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK47D6D4A5F1CB807C]    Script Date: 08/05/2014 01:48:52 ******/
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER]  WITH CHECK ADD  CONSTRAINT [FK47D6D4A5F1CB807C] FOREIGN KEY([SUBSCRIPTION_ID])
REFERENCES [dbo].[SUBSCRIPTION] ([UUID])
GO
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER] CHECK CONSTRAINT [FK47D6D4A5F1CB807C]
GO
/****** Object:  ForeignKey [FK200EAEB7F1CB807C]    Script Date: 08/05/2014 01:48:52 ******/
ALTER TABLE [dbo].[SUBSCRIPTION_PROPERTY]  WITH CHECK ADD  CONSTRAINT [FK200EAEB7F1CB807C] FOREIGN KEY([SUBSCRIPTION_ID])
REFERENCES [dbo].[SUBSCRIPTION] ([UUID])
GO
ALTER TABLE [dbo].[SUBSCRIPTION_PROPERTY] CHECK CONSTRAINT [FK200EAEB7F1CB807C]
GO
/****** Object:  ForeignKey [FKF2C75F35869350B9]    Script Date: 08/05/2014 01:48:52 ******/
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER_PRODUCT]  WITH CHECK ADD  CONSTRAINT [FKF2C75F35869350B9] FOREIGN KEY([SERVER_ID])
REFERENCES [dbo].[SUBSCRIPTION_SERVER] ([UUID])
GO
ALTER TABLE [dbo].[SUBSCRIPTION_SERVER_PRODUCT] CHECK CONSTRAINT [FKF2C75F35869350B9]
GO
/****** Object:  Table [dbo].[PROJECT]    Script Date: 08/15/2014 11:29:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROJECT](
	[UUID] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[CSA_ORGANIZATION_ID] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PROJECT] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE UNIQUE NONCLUSTERED INDEX [Name_Org] ON [dbo].[PROJECT] 
(
	[NAME] ASC,
	[CSA_ORGANIZATION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROJECT_LDAP_MAPPING]    Script Date: 08/15/2014 11:31:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROJECT_LDAP_MAPPING](
	[UUID] [nvarchar](50) NOT NULL,
	[TYPE] [nvarchar](50) NOT NULL,
	[PROJECT_ID] [nvarchar](50) NOT NULL,
	[LDAP_DN] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_PROJECT_LDAP_MAPPING] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PROJECT_LDAP_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_PROJECT_LDAP_MAPPING_PROJECT] FOREIGN KEY([PROJECT_ID])
REFERENCES [dbo].[PROJECT] ([UUID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PROJECT_LDAP_MAPPING] CHECK CONSTRAINT [FK_PROJECT_LDAP_MAPPING_PROJECT]
GO
GO

/****** Object:  Table [dbo].[SUBSCRIPTION_LOG]    Script Date: 10/11/2014 6:17:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SUBSCRIPTION_LOG](
	[UUID] [varchar](255) NOT NULL,
	[COMPONENT] [varchar](255) NULL,
	[EVENT] [varchar](255) NULL,
	[LOG_LEVEL] [varchar](255) NULL,
	[LOG_TIME] [datetime] NULL,
	[MESSAGE] [varchar](max) NULL,
	[SUBSCRIPTION_ID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SUBSCRIPTION_LOG]  WITH CHECK ADD  CONSTRAINT [FKF1B1C102F1CB807C] FOREIGN KEY([SUBSCRIPTION_ID])
REFERENCES [dbo].[SUBSCRIPTION] ([UUID])
GO

ALTER TABLE [dbo].[SUBSCRIPTION_LOG] CHECK CONSTRAINT [FKF1B1C102F1CB807C]
GO
GO
/****** Object:  Table [dbo].[PROVIDER_REGION]    Script Date: 12/8/2014 5:45:25 PM ******/
DROP TABLE [dbo].[PROVIDER_REGION]
GO
/****** Object:  Table [dbo].[DESIGN_PROVIDER_SIZE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'MESSAGE' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ALTER COLUMN MESSAGE varchar(max) NULL;
END  
ELSE
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ADD MESSAGE varchar(max) NULL;
END 
GO

IF EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'LOG_DETAIL' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ALTER COLUMN LOG_DETAIL varchar(max) NULL;
END  
ELSE
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] ADD LOG_DETAIL varchar(max) NULL;
END 
GO

IF NOT EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'LOG_PATH' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] add LOG_PATH varchar(255) NULL;
END  
GO

IF NOT EXISTS(SELECT * FROM sys.columns
	WHERE Name = N'LOG_TAG' AND OBJECT_ID = OBJECT_ID(N'[dbo].[SUBSCRIPTION_LOG]'))
BEGIN
	ALTER TABLE [dbo].[SUBSCRIPTION_LOG] add LOG_TAG varchar(255) NULL;
END 
GO

CREATE TABLE [dbo].[DESIGN_PROVIDER_SIZE](
	[UUID] [varchar](255) NOT NULL,
	[SERVICE_DESIGN_ID] [varchar](255) NOT NULL,
	[PROVIDER_SIZE_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DESIGN_PROVIDER_SIZE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORG_PROVIDER_SIZE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORG_PROVIDER_SIZE](
	[UUID] [varchar](255) NOT NULL,
	[ORG_ID] [varchar](255) NOT NULL,
	[PROVIDER_SIZE_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ORG_PROVIDER_SIZE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_REGION]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_REGION](
	[UUID] [varchar](255) NOT NULL,
	[PROVIDER_TYPE_ID] [varchar](255) NOT NULL,
	[REGION_NAME] [varchar](255) NOT NULL,
	[REGION_DISPLAY_NAME] [varchar](255) NOT NULL,
 CONSTRAINT [PK_PROVIDER_REGION] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_regionname]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_regionname] ON [dbo].[PROVIDER_REGION]
(
	[PROVIDER_TYPE_ID] ASC,
	[REGION_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_REGION_AZ]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_REGION_AZ](
	[UUID] [varchar](255) NOT NULL,
	[REGION_ID] [varchar](255) NOT NULL,
	[AZ] [varchar](255) NOT NULL,
 CONSTRAINT [PK_PROVIDER_REGION_AZ] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_regionname]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [region_az] ON [dbo].[PROVIDER_REGION_AZ]
(
	[REGION_ID] ASC,
	[AZ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_SIZE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_SIZE](
	[UUID] [varchar](255) NOT NULL,
	[PROVIDER_TYPE_ID] [varchar](255) NOT NULL,
	[SIZE] [varchar](255) NOT NULL,
	[DISPLAY_NAME] [varchar](255) NULL,
	[FLAVOR] [varchar](255) NULL,
	[VCPU] [varchar](255) NULL,
	[VMEMORY] [varchar](255) NULL,
 CONSTRAINT [PK_PROVIDER_SIZE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_size]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_size] ON [dbo].[PROVIDER_SIZE]
(
	[PROVIDER_TYPE_ID] ASC,
	[SIZE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [type_size]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_displayname] ON [dbo].[PROVIDER_SIZE]
(
	[PROVIDER_TYPE_ID] ASC,
	[DISPLAY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROVIDER_TYPE]    Script Date: 12/8/2014 11:01:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROVIDER_TYPE](
	[UUID] [varchar](255) NOT NULL,
	[TYPE] [varchar](255) NOT NULL,
	[SUB_TYPE] [varchar](255) NOT NULL,
 CONSTRAINT [PK_PROVIDER_TYPE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [type_subtype]    Script Date: 12/10/2014 1:06:44 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [type_subtype] ON [dbo].[PROVIDER_TYPE]
(
	[TYPE] ASC,
	[SUB_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORG_PROVIDER_REGION]    Script Date: 1/6/2015 9:45:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORG_PROVIDER_REGION](
	[UUID] [nvarchar](255) NOT NULL,
	[ORG_ID] [varchar](255) NOT NULL,
	[PROVIDER_REGION_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ORG_PROVIDER_REGION] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORG_PROVIDER_TYPE]    Script Date: 1/6/2015 9:46:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORG_PROVIDER_TYPE](
	[UUID] [varchar](255) NOT NULL,
	[ORG_ID] [varchar](255) NOT NULL,
	[PROVIDER_TYPE_ID] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ORG_PROVIDER_TYPE] PRIMARY KEY CLUSTERED 
(
	[UUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[ORG_PROVIDER_TYPE]  WITH CHECK ADD  CONSTRAINT [FK_ORG_PROVIDER_TYPE_PROVIDER_TYPE] FOREIGN KEY([PROVIDER_TYPE_ID])
REFERENCES [dbo].[PROVIDER_TYPE] ([UUID])
GO
ALTER TABLE [dbo].[ORG_PROVIDER_TYPE] CHECK CONSTRAINT [FK_ORG_PROVIDER_TYPE_PROVIDER_TYPE]
GO
ALTER TABLE [dbo].[ORG_PROVIDER_REGION]  WITH CHECK ADD  CONSTRAINT [FK_ORG_PROVIDER_REGION_PROVIDER_REGION] FOREIGN KEY([PROVIDER_REGION_ID])
REFERENCES [dbo].[PROVIDER_REGION] ([UUID])
GO
ALTER TABLE [dbo].[ORG_PROVIDER_REGION] CHECK CONSTRAINT [FK_ORG_PROVIDER_REGION_PROVIDER_REGION]
GO
ALTER TABLE [dbo].[DESIGN_PROVIDER_SIZE]  WITH CHECK ADD  CONSTRAINT [FK_DESIGN_PROVIDER_SIZE_PROVIDER_SIZE] FOREIGN KEY([PROVIDER_SIZE_ID])
REFERENCES [dbo].[PROVIDER_SIZE] ([UUID])
GO
ALTER TABLE [dbo].[DESIGN_PROVIDER_SIZE] CHECK CONSTRAINT [FK_DESIGN_PROVIDER_SIZE_PROVIDER_SIZE]
GO
ALTER TABLE [dbo].[ORG_PROVIDER_SIZE]  WITH CHECK ADD  CONSTRAINT [FK_ORG_PROVIDER_SIZE_PROVIDER_SIZE] FOREIGN KEY([PROVIDER_SIZE_ID])
REFERENCES [dbo].[PROVIDER_SIZE] ([UUID])
GO
ALTER TABLE [dbo].[ORG_PROVIDER_SIZE] CHECK CONSTRAINT [FK_ORG_PROVIDER_SIZE_PROVIDER_SIZE]
GO
ALTER TABLE [dbo].[PROVIDER_REGION]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_REGION_PROVIDER_TYPE] FOREIGN KEY([PROVIDER_TYPE_ID])
REFERENCES [dbo].[PROVIDER_TYPE] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_REGION] CHECK CONSTRAINT [FK_PROVIDER_REGION_PROVIDER_TYPE]
GO
ALTER TABLE [dbo].[PROVIDER_REGION_AZ]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_REGION_AZ_PROVIDER_REGION] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[PROVIDER_REGION] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_REGION_AZ] CHECK CONSTRAINT [FK_PROVIDER_REGION_AZ_PROVIDER_REGION]
GO
ALTER TABLE [dbo].[PROVIDER_SIZE]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_SIZE_PROVIDER_TYPE] FOREIGN KEY([PROVIDER_TYPE_ID])
REFERENCES [dbo].[PROVIDER_TYPE] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_SIZE] CHECK CONSTRAINT [FK_PROVIDER_SIZE_PROVIDER_TYPE]
GO
ALTER TABLE [dbo].[PROVIDER_KEY] WITH CHECK ADD	[REGION_ID] [varchar](255) NULL
GO
ALTER TABLE [dbo].[PROVIDER_KEY]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDER_KEY_PROVIDER_REGION] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[PROVIDER_REGION] ([UUID])
GO
ALTER TABLE [dbo].[PROVIDER_KEY] CHECK CONSTRAINT [FK_PROVIDER_KEY_PROVIDER_REGION]
GO

INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'hpcs', 'hpcs')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'ospool', 'default')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'vmware', 'octo')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'openstack', 'openstackInstance')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'ecsvpc', 'rhel')
GO
INSERT INTO dbo.PROVIDER_TYPE([UUID], [TYPE], [SUB_TYPE])
VALUES(NEWID(), 'ecsvpc', 'windows')
GO

INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'xsmall', 'standard.xsmall', '1', '1', 'standard.xsmall(1vcpu, 1G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'small', 'standard.small', '2', '2', 'standard.small(2vcpu, 2G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'medium', 'standard.medium', '2', '4', 'standard.medium(2vcpu, 4G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'large', 'standard.large', '4', '8', 'standard.large(4vcpu, 8G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'xlarge', 'standard.xlarge', '4', '15', 'standard.xlarge(4vcpu, 15G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'highmemlarge', 'highmem.large', '4', '16', 'highmem.large(4vcpu, 16G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), '2xlarge', 'standard.2xlarge', '8', '30', 'standard.2xlarge(8vcpu, 30G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'highmemxlarge', 'highmem.xlarge', '4', '30', 'highmem.xlarge(4vcpu, 30G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), '4xlarge', 'standard.4xlarge', '12', '60', 'standard.4xlarge(12vcpu, 60G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'highmem2xlarge', 'highmem.2xlarge', '8', '60', 'highmem.2xlarge(8vcpu, 60G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), '8xlarge', 'standard.8xlarge', '16', '120', 'standard.8xlarge(16vcpu, 120G vmemory)')


GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'small', 'small', '2', '4', 'small')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'medium', 'medium', '4', '8', 'medium')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'large', 'large', '8', '16', 'large')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ospool' and SUB_TYPE='default'), 'xlarge', 'xlarge', '16', '32', 'xlarge')

GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'small', 'small', '2', '2', 'small(2vcpu, 2G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'medium', 'medium', '2', '4', 'medium(2vcpu, 4G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'large', 'large', '4', '8', 'large(4vcpu, 8G vmemory)')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='vmware' and SUB_TYPE='octo'), 'xlarge', 'xlarge', '4', '16', 'xlarge(4vcpu, 16G vmemory)')
GO

GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'small_highperformance', 'f8924475-40d0-3840-8491-83faa3109b1b', '2', '4', 'High Performance Server - 2vCPU 4GMemory')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'small_standarad', 'c0c3a9fb-8385-38e0-ba46-adadde9af3bf', '2', '4', 'Standard Client Managed Server - 2vCPU 4GMemory')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'xsmall_highperformance', '7fe3d16a-83f6-33a0-a7f1-c029536bebe7', '1', '2', 'High Performance Server - 1vCPU 2GMemory')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='rhel'), 'xsmall_standard', 'b219f59c-2dd5-36ab-badb-cecfc2277659', '1', '2', 'Standard Client Managed Server - 1vCPU 2GMemory')

GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'small_highperformance', '27bc42aa-eb15-30e8-b949-a69ebeb4eb4c', '2', '4', 'High Performance Server - 2vCPU 4GMemory')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'small_standarad', 'afc26371-29ad-3044-85e0-7d2c0e6b0688', '2', '4', 'Standard Client Managed Server - 2vCPU 4GMemory')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'xsmall_highperformance', 'b59c21a0-78fd-3074-a675-0e91ed19fb21', '1', '2', 'High Performance Server - 1vCPU 2GMemory')
GO
INSERT INTO dbo.PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='ecsvpc' and SUB_TYPE='windows'), 'xsmall_standard', '6412121c-bb2d-32cb-9e46-0cfee7046be2', '1', '2', 'Standard Client Managed Server - 1vCPU 2GMemory')



INSERT INTO dbo.PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME, REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'region-a.geo-1', 'US WEST')
GO
INSERT INTO dbo.PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_TYPE WHERE TYPE='hpcs' and SUB_TYPE='hpcs'), 'region-b.geo-1', 'US EAST')

GO

INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1'), 'az1')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1'), 'az2')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1'), 'az3')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1'), 'az1')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1'), 'az2')
GO
INSERT INTO dbo.PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1'), 'az3')
GO


UPDATE [dbo].[PROVIDER_KEY]
   SET [REGION_ID] = (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-a.geo-1')
WHERE [REGION_NAME] ='region-a.geo-1'
GO
GO
UPDATE [dbo].[PROVIDER_KEY]
   SET [REGION_ID] = (SELECT UUID FROM dbo.PROVIDER_REGION WHERE REGION_NAME='region-b.geo-1')
WHERE [REGION_NAME] ='region-b.geo-1'
GO

INSERT INTO PROVIDER_TYPE(UUID, TYPE, SUB_TYPE)
VALUES(NEWID(), 'aws', 'ec2');


INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.medium', 'm3.medium', '1', '3.75', 'm3.medium(1vcpu, 3.75G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.large', 'm3.large', '2', '7.5', 'm3.large(2vcpu, 7.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.xlarge', 'm3.xlarge', '4', '15', 'm3.xlarge(2vcpu, 15G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm3.2xlarge', 'm3.2xlarge', '8', '30', 'm3.2xlarge(8vcpu, 30G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.small', 'm1.small', '1', '1.7', 'm1.small(1vcpu, 1.7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.medium', 'm1.medium', '1', '3.7', 'm1.medium(1vcpu, 3.7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.large', 'm1.large', '2', '7.5', 'm1.large(2vcpu, 7.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm1.xlarge', 'm1.xlarge', '4', '15', 'm1.xlarge(4vcpu, 15G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.large', 'c3.large', '2', '3.75', 'c3.large(2vcpu, 3.75G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.xlarge', 'c3.xlarge', '4', '7.5', 'c3.xlarge(4vcpu, 7.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.2xlarge', 'c3.2xlarge', '8', '15', 'c3.2xlarge(8vcpu, 15G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.4xlarge', 'c3.4xlarge', '16', '30', 'c3.4xlarge(16vcpu, 30G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c3.8xlarge', 'c3.8xlarge', '32', '60', 'c3.8xlarge(16vcpu, 30G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c1.medium', 'c1.medium', '2', '1.7', 'c1.medium(2vcpu, 1.7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'c1.xlarge', 'c1.xlarge', '8', '7', 'c1.xlarge(8vcpu, 7G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm2.xlarge', 'm2.xlarge', '2', '17.1', 'm2.xlarge(2vcpu, 17.1G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm2.2xlarge', 'm2.2xlarge', '4', '34.2', 'm2.2xlarge(4vcpu, 34.2G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'm2.4xlarge', 'm2.4xlarge', '8', '68.4', 'm2.4xlarge(8vcpu, 68.4G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'hi1.4xlarge', 'hi1.4xlarge', '16', '60.5', 'hi1.4xlarge(16vcpu, 60.5G vmemory)');
INSERT INTO PROVIDER_SIZE(UUID, PROVIDER_TYPE_ID, SIZE, FLAVOR, VCPU, VMEMORY, DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'hs1.8xlarge', 'hs1.8xlarge', '16', '117', 'hs1.8xlarge(16vcpu, 117G vmemory)');



INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'us-east-1','US East (N.Virginia)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'us-west-2','US West (Oregon)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'us-west-1','US West (N. California)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'eu-west-1','EU (Ireland)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'ap-southeast-1','Asia Pacific (Singapore)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'ap-southeast-2','Asia Pacific (Sydney)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'ap-northeast-1','Asia Pacific (Tokyo)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'sa-east-1','South America (Sao Paulo)');
INSERT INTO PROVIDER_REGION(UUID, PROVIDER_TYPE_ID, REGION_NAME,REGION_DISPLAY_NAME)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_TYPE WHERE TYPE='aws' and SUB_TYPE='ec2'), 'eu-central-1','EU (Frankfurt)');

INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1d');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-east-1'), 'us-east-1e');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-2'), 'us-west-2a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-2'), 'us-west-2b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-2'), 'us-west-2c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-1'), 'us-west-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='us-west-1'), 'us-west-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-west-1'), 'eu-west-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-west-1'), 'eu-west-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-west-1'), 'eu-west-1c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-central-1'), 'eu-central-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-central-1'), 'eu-central-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='eu-central-1'), 'eu-central-1c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-1'), 'ap-southeast-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-1'), 'ap-southeast-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-northeast-1'), 'ap-northeast-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-northeast-1'), 'ap-northeast-1b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-northeast-1'), 'ap-northeast-1c');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-2'), 'ap-southeast-2a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='ap-southeast-2'), 'ap-southeast-2b');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='sa-east-1'), 'sa-east-1a');
INSERT INTO PROVIDER_REGION_AZ(UUID, REGION_ID, AZ)
VALUES(NEWID(), (SELECT UUID FROM PROVIDER_REGION WHERE REGION_NAME='sa-east-1'), 'sa-east-1b');

GO