//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 11:40:33 AM CST 
//


package com.hp.es.cto.sp.persistence.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for context_node_import complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="context_node_import">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="child_node_import" type="{http://www.hp.com/es/cto/sp/context/jaxb}context_node_import" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="display_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="context_metadata" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "context_node_import", propOrder = {
    "childNodeImport"
})
public class ContextNodeImport {

    @XmlElement(name = "child_node_import")
    protected List<ContextNodeImport> childNodeImport;
    @XmlAttribute
    protected String name;
    @XmlAttribute(name = "display_name")
    protected String displayName;
    @XmlAttribute(name = "context_metadata")
    protected String contextMetadata;

    /**
     * Gets the value of the childNodeImport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childNodeImport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildNodeImport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContextNodeImport }
     * 
     * 
     */
    public List<ContextNodeImport> getChildNodeImport() {
        if (childNodeImport == null) {
            childNodeImport = new ArrayList<ContextNodeImport>();
        }
        return this.childNodeImport;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the contextMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextMetadata() {
        return contextMetadata;
    }

    /**
     * Sets the value of the contextMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextMetadata(String value) {
        this.contextMetadata = value;
    }

}
