//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 11:40:33 AM CST 
//


package com.hp.es.cto.sp.persistence.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for context_import complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="context_import">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="context_metadata_import" type="{http://www.hp.com/es/cto/sp/context/jaxb}context_metadata_import" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="context_node_import" type="{http://www.hp.com/es/cto/sp/context/jaxb}context_node_import"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "context_import", propOrder = {
    "contextMetadataImport",
    "contextNodeImport"
})
@XmlRootElement(name="context_import") 
public class ContextImport {

    @XmlElement(name = "context_metadata_import")
    protected List<ContextMetadataImport> contextMetadataImport;
    @XmlElement(name = "context_node_import", required = true)
    protected ContextNodeImport contextNodeImport;

    /**
     * Gets the value of the contextMetadataImport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextMetadataImport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextMetadataImport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContextMetadataImport }
     * 
     * 
     */
    public List<ContextMetadataImport> getContextMetadataImport() {
        if (contextMetadataImport == null) {
            contextMetadataImport = new ArrayList<ContextMetadataImport>();
        }
        return this.contextMetadataImport;
    }

    /**
     * Gets the value of the contextNodeImport property.
     * 
     * @return
     *     possible object is
     *     {@link ContextNodeImport }
     *     
     */
    public ContextNodeImport getContextNodeImport() {
        return contextNodeImport;
    }

    /**
     * Sets the value of the contextNodeImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextNodeImport }
     *     
     */
    public void setContextNodeImport(ContextNodeImport value) {
        this.contextNodeImport = value;
    }

}
